export const ACTION_CHANGE_FIRST_NAME = 'ACTION_CHANGE_FIRST_NAME';
export const ACTION_CHANGE_SECOND_NAME = 'ACTION_CHANGE_SECOND_NAME';
export const ACTION_PUT_DATA = 'ACTION_PUT_DATA';
export const ACTION_LOAD_DATA = 'ACTION_LOAD_DATA';